opalikha_project/goods/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'goods'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path(
        'category/<slug:category_slug>/',
        views.CategoryListView.as_view(), name='detail')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opalikha_project/opalikha_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls', namespace='pages')),
    path('', include('goods.urls', namespace='goods')),
]

opalikha_project/pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.AboutTemplateView.as_view(), name='about'),
    path('contacts/', views.ContactsTemplateView.as_view(), name='contacts'),
    path('delivery/', views.DeliveryTemplateView.as_view(), name='delivery')
]

opalikha_project/goods/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')
    slug = models.SlugField(
        unique=True,
        verbose_name='Идентификатор',
        help_text=('Идентификатор страницы для URL; разрешены символы '
                   'латиницы, цифры, дефис и подчёркивание.')
    )
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='category_pictures',
        blank=True,
        null=True
    )

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Good(models.Model):
    title = models.CharField(max_length=256, verbose_name='Название')
    price = models.DecimalField(
        verbose_name='Цена', max_digits=10, decimal_places=2, blank=True
    )
    description = models.TextField(
        default='Нет описания', verbose_name='Описание товара'
    )
    image = models.ImageField(
        'Изображение', upload_to='goods_pictures', blank=True, null=True
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Создан'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='Обновлен'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Категория'
    )

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'
        default_related_name = 'goods'

    def __str__(self):
        return self.title

opalikha_project/pages/models.py
from django.db import models

# Create your models here.

opalikha_project/users/models.py
from django.contrib.auth.models import AbstractUser


class MyUser(AbstractUser):
    pass

opalikha_project/goods/views.py
from django.shortcuts import render, get_object_or_404

from django.views.generic import ListView

from .models import Category


class IndexListView(ListView):
    model = Category
    template_name = 'goods/index_list.html'


class CategoryListView(ListView):
    template_name = 'goods/category.html'

    def get_queryset(self):
        self.category = get_object_or_404(
            Category,
            slug=self.kwargs.get('category_slug')
        )
        return self.category.goods.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context

opalikha_project/pages/views.py
from django.views.generic import TemplateView


class AboutTemplateView(TemplateView):
    template_name = 'pages/about.html'


class ContactsTemplateView(TemplateView):
    template_name = 'pages/contacts.html'

class DeliveryTemplateView(TemplateView):
    template_name = 'pages/delivery.html'

opalikha_project/users/views.py
from django.shortcuts import render

# Create your views here.

opalikha_project/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}"> -->
    <title>
      {% block title %}{% endblock %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

opalikha_project/templates/goods/category.html
{% extends "base.html" %}
{% block title %}
  Товары в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h2 class="text-center">Товары в категории {{ category.title }}</h2>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for good in object_list %}
    <article class="mb-5">  
      {% include "includes/good_card.html" %}
    </article>   
  {% endfor %}
{% endblock %}

opalikha_project/templates/goods/index_list.html
{% extends 'base.html' %}
{% block title %}
  Главная страница
{% endblock %}
{% block content %}
  {% for category in object_list %}
    <article class="mb-5">
      {% include "includes/category_card.html" %}
    </article>
  {% endfor %}
{% endblock %}

opalikha_project/templates/includes/category_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      <!-- {% if post.image %}
        <a href="{{ category.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ category.image.url }}">
        </a>
      {% endif %} -->
      <h5 class="card-title">{{ category.title }}</h5>
      <p class="card-text">{{ category.description }}</p>
      <a href="{% url 'goods:detail' category.slug %}" class="card-link">К категории</a>
    </div>
  </div>
</div>

opalikha_project/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Корма-Опалиха. 2025</p>    
</footer>

opalikha_project/templates/includes/good_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if good.image %}
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ good.image.url }}">
      {% endif %}
      <h5 class="card-title">{{ good.title }}</h5>
      <p class="card-text">{{ good.price }} р.</p>
      <p class="card-text">{{ good.description }}</p>
    </div>
  </div>
</div>

opalikha_project/templates/includes/header.html
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'goods:index' %}">
        <h2>Корма-Опалиха</h2>
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О нас
            </a>
          </li>
          <li>
            <a class="nav-link {% if view_name == 'pages:contacts' %} text-white {% endif %}" href="{% url 'pages:contacts' %}">
              Контакты
            </a>
          </li>
          <li>
            <a class="nav-link {% if view_name == 'pages:delivery' %} text-white {% endif %}" href="{% url 'pages:delivery' %}">
              Доставка
            </a>
          </li>
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

opalikha_project/templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О нас
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        О нас
      </div>
      <div class="card-body">
        <p>
          Опалиха
        </p>
        <p>
          Лучшие корма в Красногорске
        </p>
        <p>
          Широкий ассортимент
        </p>
      </div>
    </div>
  </div>
{% endblock %}

opalikha_project/templates/pages/contacts.html
{% extends "base.html" %}
{% block title %}
  Контакты
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header">
      Контакты
    </div>
    <div class="card-body">
      <p>
        Г. Красногорск, мкр. Опалиха, ул. Советский переулок, 10/5
      </p>
      <p>
        opaliha_korma@gmail.com
      </p>
      <p>
        8(905)888-55-80
      </p>
    </div>
  </div>
</div>
{% endblock %}

opalikha_project/templates/pages/delivery.html
{% extends "base.html" %}
{% block title %}
  Доставка
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-header">
      Доставка
    </div>
    <div class="card-body">
      <p>
        Условия доставки
      </p>
      <p>
        Цены
      </p>
      <p>
        8(905)888-55-80
      </p>
    </div>
  </div>
</div>
{% endblock %}